const express = require('express');
const {loginUser, loginAdmin} = require('../controllers/authController');

const authRouter = express.Router();
authRouter.post('/login',loginUser); // this is the authRouter registration....
authRouter.post('/login/admin',loginAdmin) // this is the authRouter for login only the admin user....
module.exports = authRouter; // exporting the authRouter....